version: '3.3'

services:
  web:
    build: .
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - DATABASE_NAME=urlshortener
      - JWT_SECRET=your-secret
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:


