version: '3.3'

services:
  web:
    build: .
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 3000:3000
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_NAME=urlshortener
      - JWT_SECRET=your-secret
    restart: on-failure
  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - urlshortener-db:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=urlshortener
      - MYSQL_ROOT_PASSWORD=password
volumes:
  urlshortener-db:


